### ISSUE TITLE
Attribute Path API

### ISSUE THREAD

**Issue by alelb** [fabbricadigitale/scimd#32]
It's need an API thats  for a given attribute path returns the related set of schema attributes.

**Comment by leogr** [comment]
Also, we need to pay attention to case sensitivity (refs #3)

**Comment by leogr** [comment]
By https://github.com/fabbricadigitale/scimd/commit/a34e3f820db8bbdcb5bb20ef0893aeb8c5d1dd81 , I introduced the ability described above.

However, it's not enough because the `ResourceType` must be known to accomplish that.
So, given a search query that has a filter and an endpoint (ie. `/Users` or `/` for root queries),  another component is needed to prepare things (ie. lookup proper `ResourceType`, that could be more than one in case of root queries).

I think `api.Search` should incapsulate all required info, so may be we could put the needed resource type into it.

**Comment by leogr** [comment]
Since https://github.com/fabbricadigitale/scimd/commit/62b7a325fe571ee012972a39bd8b6291744b38aa you should have what you need!

@alelb Let me know!
