### ISSUE TITLE
Clarification about readOnly attributes

### ISSUE THREAD

**Issue by alelb** [fabbricadigitale/scimd#81]
As noticed in this [thread](https://www.ietf.org/mail-archive/web/scim/current/msg01089.html), scim spec is ambiguous about readOnly attributes. 

We should be able to set a non-core readOnly attribute, like **groups** attribute in **User** resource.
At the moment we are not able to do this.

A readOnly attribute that is not set by the SPC, it should be created by a POST, but it cannot be modified by a PUT or a PATCH.

cc @leogr @leodido

**Comment by leodido** [comment]
That thread is 2013 ... Referring to SCIM v1 ?

**Comment by alelb** [comment]
You're right, it's referring to SCIM v1, but I remain in doubt concerns readOnly attributes. 
In the case of non-core attributes, the client can or cannot directly set a readOnly property? If it cannot do that, the readOnly properties are just "computed" attributes?

**Comment by leogr** [comment]
I think this question is wrong.

> readOnly  The attribute SHALL NOT be modified.
Simply It means that scim client cannot modify those values, so HTTP API must ti handle that as RFC mandates:
> For example, in a SCIM PUT request,
   "readOnly" attributes are ignored, while "readWrite" attributes are
   updated.  There is no need for a SCIM client to discover which
   attributes are "readOnly", and the client does not need to remove
   them from a PUT request in order to be accepted. 

That's It.

Buy what you want it's different, check out this:

> immutable  The attribute MAY be defined at resource creation
            (e.g., POST) or at record replacement via a request (e.g., a
            PUT).  The attribute SHALL NOT be updated.

https://tools.ietf.org/html/rfc7643#section-7

**Comment by alelb** [comment]
According to rfc, I suppose that the readOnly attributes are setted from the service provider.
So I'll close this discussion.
Tnk!
